mock: true
api:
  getBooks:
    mock: true
  getBlogs:
    mock: false
  getImages:
    mock: true
  getContainers:
    mock: true
  getSSL:
    mock: true
mongodb:
  host: "localhost"
  port: 27017
  database: "vue"
  username: "rootuser"
  password: "rootpass"
